baseurl = "https://donvince.com/"
title = "Idea Gallery"
languageCode = "en-gb"
theme = "paperback"

[params]
AuthorName = "Don Vince"
Tagline = "my online notebook"

SocialLinks = true
GithubUsername = "donvince"
TwitterUsername = "donaldvince"
